export const achievementList = [ 
    { id: 1, unlocked: false, shouldBeUnlcoked: (state) => state.numberOfDiamonds >= 1,
        name: 'Your first diamond!', note: 'dig 1 diamond'}, 
    { id: 2, unlocked: false, shouldBeUnlcoked: (state) => state.numberOfDiamonds >= 10 ,
        name: 'Getting better!', note: 'dig 10 diamond'},
    { id: 3, unlocked: false, shouldBeUnlcoked: (state) => state.numberOfDiamonds >= 100 ,
        name: 'Preety nice!', note: 'dig 100 diamond'}, 
    { id: 4, unlocked: false, shouldBeUnlcoked: (state) => state.numberOfDiamonds >= 1000 ,
        name: 'DIAMOND DIGGER', note: 'dig 1000 diamond'}, 
    { id: 5, unlocked: false, shouldBeUnlcoked: (state) => state.numberOfDiamonds >= 5000 ,
        name: 'WOW!', note: 'dig 5000 diamond'},
    { id: 6, unlocked: false, shouldBeUnlcoked: (state) => state.items[0].amount === 1 ,
        name: 'Helpful hand!', note: 'buy 1 hand'}, 
    { id: 7, unlocked: false, shouldBeUnlcoked: (state) => state.items[0].amount === 10 ,
        name: 'Even more hands', note: 'buy 5 hands'}, 
    { id: 8, unlocked: false, shouldBeUnlcoked: (state) => state.items[0].amount === 50 ,
        name: 'Alien?', note: 'buy 50 hands'},
    { id: 9, unlocked: false, shouldBeUnlcoked: (state) => state.items[1].amount === 1 ,
        name: 'Better than hand', note: 'buy 1 stick'}, 
    { id: 10, unlocked: false, shouldBeUnlcoked: (state) => state.items[1].amount === 10 ,
        name: 'Making bonefire?', note: 'buy 5 sticks'}, 
    { id: 11, unlocked: false, shouldBeUnlcoked: (state) => state.items[1].amount === 50 ,
        name: 'Wooden Guy', note: 'buy 50 sticks'},
    { id: 12, unlocked: false, shouldBeUnlcoked: (state) => state.items[2].amount === 1 ,
        name: 'First pick!', note: 'buy 1 wooden pick'}, 
    { id: 13, unlocked: false, shouldBeUnlcoked: (state) => state.items[2].amount === 10 ,
        name: 'actually these are weak', note: 'buy 5 wooden picks'}, 
    { id: 14, unlocked: false, shouldBeUnlcoked: (state) => state.items[2].amount === 50 ,
        name: 'Really like wood?', note: 'buy 50 wooden picks'},
    { id: 15, unlocked: false, shouldBeUnlcoked: (state) => state.items[3].amount === 1 ,
        name: 'better version of the previous one!', note: 'buy 1 stone pick'}, 
    { id: 16, unlocked: false, shouldBeUnlcoked: (state) => state.items[3].amount === 10 ,
        name: 'go go digger!', note: 'buy 5 stone picks'}, 
    { id: 17, unlocked: false, shouldBeUnlcoked: (state) => state.items[3].amount === 50 ,
        name: 'Stone stone stone', note: 'buy 50 stone picks'},
    { id: 18, unlocked: false, shouldBeUnlcoked: (state) => state.items[4].amount === 10 ,
        name: 'Finally iron!', note: 'buy 1 iron pick'}, 
    { id: 19, unlocked: false, shouldBeUnlcoked: (state) => state.items[4].amount === 5 ,
        name: 'Iron looks nice', note: 'buy 5 iron picks'}, 
    { id: 20, unlocked: false, shouldBeUnlcoked: (state) => state.items[4].amount === 50 ,
        name: 'are they heavy?', note: 'buy 50 iron picks'},
    { id: 21, unlocked: false, shouldBeUnlcoked: (state) => state.items[5].amount === 10 ,
        name: 'Why did you buy it?', note: 'buy 1 golden pick'}, 
    { id: 22, unlocked: false, shouldBeUnlcoked: (state) => state.items[5].amount === 5 ,
        name: 'iron is better acutally', note: 'buy 5 golden picks'}, 
    { id: 23, unlocked: false, shouldBeUnlcoked: (state) => state.items[5].amount === 50 ,
        name: 'STOP IT!', note: 'buy 50 golden picks'},
    { id: 24, unlocked: false, shouldBeUnlcoked: (state) => state.items[6].amount === 10 ,
        name: 'shiny *.*', note: 'buy 1 diamond picks'}, 
    { id: 25, unlocked: false, shouldBeUnlcoked: (state) => state.items[6].amount === 5 ,
        name: 'these are good!', note: 'buy 5 diamond picks'}, 
    { id: 26, unlocked: false, shouldBeUnlcoked: (state) => state.items[6].amount === 50 ,
        name: 'Nice collection', note: 'buy 50 diamond picks'},
    { id: 27, unlocked: false, shouldBeUnlcoked: (state) => state.items[7].amount === 1 ,
        name: 'BOOOOM!', note: 'buy 1 tnt'}, 
    { id: 28, unlocked: false, shouldBeUnlcoked: (state) => state.items[7].amount === 5 ,
        name: 'can you deal with them?', note: 'buy 5 tnt'}, 
    { id: 29, unlocked: false, shouldBeUnlcoked: (state) => state.items[7].amount === 50 ,
        name: 'it\'s probably dangerous', note: 'buy 50 tnt'},
    { id: 30, unlocked: false, shouldBeUnlcoked: (state) => state.items[8].amount === 10 ,
        name: '', note: 'buy 1 creeper'}, 
    { id: 31, unlocked: false, shouldBeUnlcoked: (state) => state.items[8].amount === 5 ,
        name: 'Even more hands', note: 'buy 5 creepers'}, 
    { id: 32, unlocked: false, shouldBeUnlcoked: (state) => state.items[8].amount === 50 ,
        name: 'Tons of hands!', note: 'buy 50 creepers'}
]
