export const shopItems = [ 
    { name: 'hand', amount: 0, cost: 5, increaseCostValue: 3,
        lvlNeeded: 1, diamondsPerSecond: 0, diamondsPerClick: 1}, 
    { name: 'stick', amount: 0, cost: 50, increaseCostValue: 5,
        lvlNeeded: 3, diamondsPerSecond: 10}, 
    { name: 'wooden Pick', amount: 0, cost: 500, increaseCostValue: 8,
        lvlNeeded: 5, diamondsPerSecond: 25},
    { name: 'stone Pick', amount: 0, cost: 2500, increaseCostValue: 11, 
        lvlNeeded: 8, diamondsPerSecond: 50},  
    { name: 'iron Pick', amount: 0, cost: 5000, increaseCostValue: 13,
        lvlNeeded: 9, diamondsPerSecond: 100}, 
    { name: 'golden Pick', amount: 0, cost: 75000, increaseCostValue: 17,
        lvlNeeded: 10, diamondsPerSecond: 250},
    { name: 'diamond Pick', amount: 0, cost: 15000, increaseCostValue: 20,
        lvlNeeded: 12, diamondsPerSecond: 500}, 
    { name: 'tnt', amount: 0, cost: 50000, increaseCostValue: 25,
        lvlNeeded: 14, diamondsPerSecond: 1000}, 
    { name: 'creeper', amount: 0, cost: 100000, increaseCostValue: 50,
        lvlNeeded: 15   , diamondsPerSecond: 5000},
];
