export const shopItems = [ 
    { name: 'hand', amount: 0, cost: 5, increaseCostValue: 2,
        lvlNeeded: 1, diamondsPerSecond: 0, diamondsPerClick: 1, note:'"everyone used to start"'}, 
    { name: 'stick', amount: 0, cost: 50, increaseCostValue: 3,
        lvlNeeded: 3, diamondsPerSecond: 10, note:'"better than hand!"'}, 
    { name: 'wooden pickaxe', amount: 0, cost: 500, increaseCostValue: 5,
        lvlNeeded: 5, diamondsPerSecond: 25, note:'"wooden pickaxe, is it possible?"'},
    { name: 'stone pickaxe', amount: 0, cost: 2500, increaseCostValue: 8, 
        lvlNeeded: 8, diamondsPerSecond: 50, note:'"finally usefull tool"'},  
    { name: 'iron pickaxe', amount: 0, cost: 5000, increaseCostValue: 10,
        lvlNeeded: 9, diamondsPerSecond: 100, note:'"better version of the previous one"'}, 
    { name: 'golden pickaxe', amount: 0, cost: 7500, increaseCostValue: 11,
        lvlNeeded: 10, diamondsPerSecond: 250, note:'"this one is weak"'},
    { name: 'diamond pickaxe', amount: 0, cost: 15000, increaseCostValue: 15,
        lvlNeeded: 12, diamondsPerSecond: 500,note:'"best of the best!"'}, 
    { name: 'tnt', amount: 0, cost: 50000, increaseCostValue: 17,
        lvlNeeded: 14, diamondsPerSecond: 1000,note:'"dangerous thing"'}, 
    { name: 'creeper', amount: 0, cost: 100000, increaseCostValue: 20,
        lvlNeeded: 15   , diamondsPerSecond: 5000,note:'"better stay away from this one!"'},
];
